// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDrU0AoFgaUwVWA58FTNqeTHCsXFYEfk',
    appId: '1:214580382406:web:8919f0f2e351de943be5c7',
    messagingSenderId: '214580382406',
    projectId: 'instagram-b4d9b',
    authDomain: 'instagram-b4d9b.firebaseapp.com',
    storageBucket: 'instagram-b4d9b.firebasestorage.app',
    measurementId: 'G-PN0NGH20KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgIadlbq8GxqDCV7HAXdoglEtDFQrJTo',
    appId: '1:214580382406:android:166cc74f51d535b43be5c7',
    messagingSenderId: '214580382406',
    projectId: 'instagram-b4d9b',
    storageBucket: 'instagram-b4d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDogbB_TtbFu5E99tcXr9f-qT4plOalZNQ',
    appId: '1:214580382406:ios:a0a1ac4a0db9551e3be5c7',
    messagingSenderId: '214580382406',
    projectId: 'instagram-b4d9b',
    storageBucket: 'instagram-b4d9b.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );
}
